### ISSUE TITLE
Plaats atoom op grid, berekend waar bindingen komen

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#118]
!! Hier moet een goed algoritme komen, met input van de chemici, dat voor enkele aangeleverde atomen bepaalt welke bindingen er zullen komen !!

Wanneer een atoom geplaats wordt op de Lewis crafting table, worden de bindingen voor alle atomen op het rooster opnieuw berekend.

(1) Bepaal waar bindingen komen
op basis van het aantal valentieelektronen ten opzichte van de edelgasconfiguratie
of (ook) op basis van of de atoomsoorten: metaal-nietmetaal, metaal-metaal, metaal-nietmetaal

(2) Bepaald watvoor bindingen het zijn
berekend het verschil in EN waarde tussen de twee atomen: DeltaEN
Als DeltaEN > 1.7, een ionenbinding
Als DeltaEN < 1.7, een covalente binding

**Comment by smtdm** [comment]
correcties:
OF
Als DeltaEN > 1.66, een ionenbinding
Als DeltaEN < 1.66, een covalente binding

OF
Als DeltaEN >= 1.7, een ionenbinding
Als DeltaEN < 1.7, een covalente binding
