### ISSUE TITLE
Show bonds on the LCT grid

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#119]
In issue #118 was berekend welke bindingen tussen welke atomen moeten komen.
De bindingen moeten getoond worden bovenop het crafting grid.

covalente binding: er komt een lijn tussen de atomen. De twee elektronen die gebonden werden mogen niet meer getoond worden.

ionenbinding: er komt een pijl van het ene atoom naar het andere. Het elektron dat is verplaatst mag niet meer getoond worden bij zijn oude atoom, maar moet (mag) getoond worden bij zijn nieuwe atoom.

**Comment by smtdm** [comment]
de pijl is een mogelijke voorstelling, maar voor sommige atomen (zoals Mg, Magnesium) gaat dit niet goed werken omdat deze 2 elektronen aan 2 verschillende atomen gaat geven. Het resultaat is een Mg^2+ ion en een zuurrest (bv [SO_4]^2-). Hoe we dit goed gaan aanpakken is nog niet helemaal duidelijk...
