### ISSUE TITLE
Lewis crafting table: recipes

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#120]
Tijdelijke oplossing: voeg één recipe toe, met atomen en stoffen die al voorhanden zijn (bv stof van Erlenmeyer, zout, of een bestaand Minecraft blok).

Voeg recipes voor chemische stoffen die via de Lewis crafting table gemaakt kunnen worden.

Bijvoorbeeld 
Na + Cl --> zout

Hiervoor moeten we een overzicht hebben van stoffen en hun recipes. We hebben al overzichtsdocumenten:
https://docs.google.com/document/d/1znEEGgsLmSSaRPgRKAQrtmq2DzMUrpX7ImWhVG6Gq7Y/edit
https://docs.google.com/spreadsheets/d/1Dt9k9M4m4czCxG8u-0TiftBncnmU4ePx6ofLZncG81M/edit#gid=0

Bekijk welke stoffen er al geïmplementeerd zijn in Minelabs (cfr. gassen en vloeistoffen in Erlenmeyer)

**Comment by JorenFa** [comment]
![image](https://user-images.githubusercontent.com/96701605/177311174-28abbfc9-4fdf-4327-9c62-ef4a36e762f4.png)
De tweede link werkt niet meer zo goed..
