### ISSUE TITLE
Lewis Crafting table: text above input slots

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#122]
Idealiter, schrijf boven ieder slot wat de speler moet aanleveren, namelijk 10 atomen van een atoom dat op het grid is geplaatst.

Bv. Na Cl op grid

Input slots:
10 Na
10 Cl

**Comment by JorenFa** [comment]
Text op een inventory is niet echt the minecraft way, dus laten we in plaats daarvan de atoom zien die in de slot moet komen op de slot zelf.
