### ISSUE TITLE
Atoms to add

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#130]
List of atoms to add:

- [x] K 
- [x] Ca
- [x] Fe
- [x] Zn
- [x] Br
- [x] Ag
- [x] Cd
- [x] Sn
- [x] I
- [x] Au
- [x] Hg
- [x] Pb
- [x] U

**Comment by smtdm** [comment]
InitialN moet nog worden aangepast worden.
itemmodels moeten nog gemaakt worden

**Comment by RandyParedis** [comment]
Hoeveel valentie-elektronen hebben de metalen? Of teken ik gewoon een wolk, omdat dat niet vast ligt?

**Comment by smtdm** [comment]
plz no. da is een moeilijk discussiepunt dus mss gewoon voorlopig geen elektronen...

**Comment by RandyParedis** [comment]
Okay! Ik zal hier in Augustus pas terug naar kunnen zien, sadly. Dus gebruik for now andere afbeeldingen ofzo.

**Comment by IneMEGAmaxi** [comment]
is added in [d28d047](https://github.com/ScicraftLearn/MineLabs/commit/d28d047c51be3e689a2030627c81ad9f50e1ddb9)
