### ISSUE TITLE
Lewis Crafting Table item classified as Misc. item and not in one of the Minelabs Tabs

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#150]
The LCT shows up in the miscellaneous item tab and not in one of the scicraft/minelabs tabs. Add tab for workstations/crafting block where the LCT should be located.

**Comment by JorenFa** [comment]
It was specifically written that way, I don't know why but if you want it changed just let me know to where and it's done.

**Comment by JorenFa** [comment]
Moved Lewis Crafting Table to the main Scicraft tab. (e48b0edb)
