### ISSUE TITLE
Putting atom back in inventory does not always work

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#152]
Both in creative and survival: after putting an atom in the LCT, putting it back in the inventory does not always work. Several tries may be needed before the item is dropped into an inventory slot.

**Comment by BillyVanhove** [comment]
wat is hier juist het probleem? ik kan geen scenario vinden waar er een probleem opduikt. Is er misschien ergens informatie over hoe je deze bug kan laten gebeuren?

**Comment by JoeyDP** [comment]
Ik geloof dat dit al opgelost is geraakt met @ferriarnus zijn refactor. Issue wordt gesloten, tenzij iemand het terug tegenkomt.
