### ISSUE TITLE
Textures to display bonds

### ISSUE THREAD

**Issue by JorenFa** [ScicraftLearn/Minelabs#157]
I need 3 simple textures for bonds:
There only needs to be one unlisted "bond" item which I will make, and using overrides it'll look different depending on NBT values.
I've added the required model files (3a1d4c76) so all that needs to be done is creating the textures and filling in the model files.
The override values I'll need are:
- "direction": 0 (horizontal) or 1 (vertical)
- "bond_amount": 1-3

**Comment by IneMEGAmaxi** [comment]
staat op lct_bond_textures branch
 commit: [8bafe98](https://github.com/ScicraftLearn/MineLabs/commit/8bafe98b712e76c26ba09087c9b648a48688131c)
