### ISSUE TITLE
Input slots not accepting correct atom for CH4

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#167]
When adding atoms in the lower slots, the visuals indicate that other atoms need to be geven than that are accepted. (see picture below)
Lefmost slot shows H but accepts C, rightmost slot shows C but accepts H

![afbeelding](https://user-images.githubusercontent.com/26555903/179213214-21c9dcd5-f802-45ec-9ced-521a2bbc3ff8.png)
![afbeelding](https://user-images.githubusercontent.com/26555903/179213273-0006d5fe-57d6-45f8-9a30-ded3310ead01.png)

**Comment by smtdm** [comment]
same problem for CO, CO2, HNO3

**Comment by JorenFa** [comment]
Fixed in 05f10dc
