### ISSUE TITLE
Strange behaviour after picking up items after breaking the LCT 

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#170]
When picking up items that were stored in the LCT, right after breaking the LCT, the stacks formed in the inventory are random an do not form one single stack. (see picture below)
The items do stack when moved in the player's inventory

This bug does not happen when breaking the LCT, waiting a couple of seconds and then picking up the items.
This bug does not happen when storing the items in another container (like a chest or furnace)

![afbeelding](https://user-images.githubusercontent.com/26555903/179224216-18e0298a-b362-4c49-a8b1-80fac591926a.png)

**Comment by JorenFa** [comment]
Fixed in ebefa34
(Forgot to add it to the commit message - whups 😅)
