### ISSUE TITLE
Inconsistent behaviour when carbon is placed either side of an atom

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#192]
Placing carbon atoms either side of some (maybe all) atoms (see picture) makes the bonds flip every tick.

![afbeelding](https://user-images.githubusercontent.com/26555903/180649045-596bac1d-838e-4d94-b2d7-1c111eb50727.png)
![afbeelding](https://user-images.githubusercontent.com/26555903/180649051-b3397053-d284-49fd-ada7-ac3a66a4c99f.png)

**Comment by JoeyDP** [comment]
To solve this we need to make the vertices a list instead of a set. I will look into this. Now the bonds are also recomputed every frame which is not ideal 😅

**Comment by JoeyDP** [comment]
How many tries did it take you to get the right screenshots by the way? :p

**Comment by smtdm** [comment]
Issue possibly fixed?

**Comment by thdaele** [comment]
Seems to be fixed on the main branch, algorithm seems to prefer the left bond over the right one but I assume this is fine since it doesn't switch anymore every tick.
