### ISSUE TITLE
Quantumfield blocks in subatomic dimension

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#201]
Quantumfields of one type arise as clusters in the subatomic dimension. A cluster contains maybe 15 quantumfieldblocks. 
Different kinds of clusters are scattered in the subatomic dimension. They are on the level of the floor of barrier blocks but also above and below the floor.

**Comment by MajaVerstraeten** [comment]
A quantumfield of one type has to appear as a cluster of ~15 blocks.

So there should be a cloud of 15 electron-quantumfieldblocks here. 
And a cloud of 1 upquark-quantumfieldblocks there

**Comment by MajaVerstraeten** [comment]
![Screenshot from 2020-12-19 15-47-05](https://user-images.githubusercontent.com/69113323/181930818-2c56c074-91e9-4525-b1da-314cef1b12a5.png)
![Screenshot from 2020-12-19 15-43-07](https://user-images.githubusercontent.com/69113323/181931441-39b3947d-682d-4342-bb5b-6812a23b5d0b.png)


It used to look like this: in a square of 5x5, for every position, there was a chance that there existed a block. So you got different patterns of clusters. Since the clusters are floating like clouds now, create them in a volume of 5x5x3 instead

**Comment by AlleeElias** [comment]
clusters now spawn in 7x7x5 sizes (can include up to 245 blocks!!)
