### ISSUE TITLE
Direction of arrow

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#222]
The direction of the arrow points along the direction of vector **E** that was calculated before. 
The arrow points towards negative charges and towards positive charges

**Comment by JoeyDP** [comment]
> The arrow points towards negative charges and towards positive charges

Should it move away from one of them?

**Comment by MajaVerstraeten** [comment]
Correct! And the way it is implemented now is in the wrong direction... Maybe my bad description was the cause... It should be
"The arrow points towards negative charges and away from positive charges".
