### ISSUE TITLE
LCT: Dragging an item shows correct molecule but does not open bottom input slots

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#223]
When dragging an atom, the ghost items in the LCT appear, but the lower inputslots are not opened. 
Closing and reopening the table shows that dragged items are not real.

Picture after H is dragged (from left to right) over O to make H2O
![afbeelding](https://user-images.githubusercontent.com/26555903/181193516-e47d5812-505e-495e-ab87-36331d9c4c73.png)

Picture after closing and re-opening the LCT. The leftmost H has disappeared.
![afbeelding](https://user-images.githubusercontent.com/26555903/181194005-b359f1eb-8fa3-452a-94ed-0254d7dfc2f0.png)

Possible correct behaviour:
- Dragged items can be used to make a molecule.

OR if that is not possible
- Do not show a dragged atom, to avoid confusing the player.

**Comment by JoeyDP** [comment]
Is this still an issue @ferriarnus

**Comment by ferriarnus** [comment]
It seems so yes

**Comment by thdaele** [comment]
Someone needs to verify that the solution for this bug suffices for now

**Comment by thdaele** [comment]
Is partially solved, forced the items to be the same on server and client. It feels a bit weird tho. Try to make a better solution where we sync client to the server and not other way around.

**Comment by pixar02** [comment]
Might be solved now @smtdm could you check `atomic_storage` branch

**Comment by JoeyDP** [comment]
Seems like it works now. Closing.
