### ISSUE TITLE
Stable nucleus

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#231]
Consider the nuclide table:
https://en.wikipedia.org/wiki/Table_of_nuclides#/media/File:NuclideMap_stitched.png

The number of neutrons is on the horizontal axis. The number of protons is on the vertical axis. So at the bottom left is a nucleus with zero neutrons and zero protons.

If the nucleus that the player has formed, corresponds to a black square on the nuclide table, the nucleus is stable. All is well

**Comment by smtdm** [comment]
example recipes (useful for testing). p = proton, n = neutron

Hydrogen
- p = 1, n = 0 -> stable
- p = 1, n = 1 -> stable
- p = 1, n >= 2 -> unstable (more n = more unstable)

Helium
- p = 2, n = 0 -> unstable
- p = 2, n = 1 -> stable
- p = 2, n = 2 -> stable
- p = 2, n >= 3 -> unstable (more n = more unstable)

Lithium
- p = 3, n <= 2 -> unstable
- p = 3, n = 3 -> stable
- p = 3, n = 4 -> stable
- p = 3, n >= 5 -> unstable

...
