### ISSUE TITLE
Unstable nucleus starts shaking

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#232]
Consider the nuclide table (see previous issue)

If the nucleus that the player has formed, DOES NOT correspond to a black square on the nuclide table, then the nucleus is unstable. 

The protons and neutrons of the nucleus start to shake. 

Optional: if the nucleus is **further away** from the black line of stable nuclides, then the nucleus **shakes harder**.

**Comment by smtdm** [comment]
additionally: when the atom is unstable, the space between the protons and neutrons becomes larger. More unstable means a larger sace between.

**Comment by MaksimKarnaukh02** [comment]
De optional van Maja kan gemakkelijk gedaan worden, en dat ga ik nu doen.
De additional van Dante is wel een klein beetje lastiger, sinds de protonen/neutronen al in een vast figuur zitten. Het beste wat kan gedaan worden denk ik, is om de scale van alle opeenvolgende figuren waarvan de eindpunten de protonen/neutronen voorstellen, groter te maken en wat verder van het middelpunt te brengen, maar dit is zowieso wat er gebeurt bij verdere protonen/neutronen. Is dit een noodzakelijke feature? Want dan zal ik dat proberen doen ook.

**Comment by MajaVerstraeten** [comment]
Ik zou zeggen dat het niet noodzakelijk is dan... Maar da's gemeen t.o.v. Dante zijn feature xD

**Comment by MaksimKarnaukh02** [comment]
Zou dat dan gewoon een eenmalige increase in space between protons/neutrons zijn bij het onstabiel worden, of zou daar ook rekening moeten gehouden worden met hoe ver we van de zwarte lijn zitten?

**Comment by MajaVerstraeten** [comment]
Ik denk dat het vooral een visueel aangename feature is en minder gebaseerd op de wetenschap maar ik kan verkeerd zijn
