### ISSUE TITLE
Let electrons fly around nucleus with specific radius

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#235]
The electron flies on a circle around the nucleus with a specific radius.

For the circle with radius 1, two electrons can fly on this circle,
For the circle with radius 2, 8 electrons can fly on this circle,
...
For the circle with radius n, 2n² electrons can fly on this circle.

When the current radius is full, start filling the next radius.

**Comment by JoeyDP** [comment]
See #230 related

**Comment by JoeyDP** [comment]
I think it might be easiest to use position functions (periodic functions that map a timestamp to a position) for rendering the electrons and making them fly around. Again this is probably easier in one central entity that handles all rendering. We can make the paths orthogonal up to 3, which gives 2 + 8 + 18 electrons (to be confirmed) and set this as a limit for now. Rendering more electrons would not be clear visually anymore and has little educational use in the current scope. Extending this further at a later time is still possible.
