### ISSUE TITLE
Entropy mobs shouldn't affect floor of subatomic dimension

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/MineLabs#256]
The entropy mob should not affect the floor of the subatomic dimension. As far as I'm concerned, it is ok if the entropy mob does not spawn in the subatomic dimension at all

The entropy mob checks if a block is "dragon immune". In that case, the mob leaves the block unaffected. Like this, bed rock is unaffected. The subatomic-floor-block should be checked in the same way >> This is done through a vanilla tag that you have to  extend (replace=false)

**Comment by JoeyDP** [comment]
Maybe there is also a property of blocks that makes them indestructable? If so, we can also check on this alongsidethe tag check we have now.

**Comment by JoeyDP** [comment]
Thomas confirmed that indestructible blocks have their hardness set to -1

![image](https://user-images.githubusercontent.com/2528391/185057443-7867858b-ead2-45b2-9dc7-c0a340884707.png)

Add this check to the entropy creeper alongside the dragon immune.
