### ISSUE TITLE
Have lewis crafting table require erlenmeyer as input again.

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/MineLabs#260]
Somewhere in the refactor it seems the check for (and consumption of) the Erlenmeyer input has been dropped. Make it a requirement for all recipes for now.

**Comment by ferriarnus** [comment]
fixed

**Comment by JoeyDP** [comment]
Could you also fix it after merging this PR please? https://github.com/ScicraftLearn/MineLabs/pull/261

**Comment by ferriarnus** [comment]
I will
