### ISSUE TITLE
The Box of Schrödinger's Cat

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#27]
Texture for the box to put our zombie cat in.

For now I suggest we go with the zombie noises and either spawning a live cat or its loot, so no new cat texture is required.

**Comment by IneMEGAmaxi** [comment]
.obj, .mtl and .png available here:
[SchrodingerChest.zip](https://github.com/ScicraftLearn/Scicraft/files/7652427/SchrodingerChest.zip)
Colours of the cat can be changed if we want to (Photoshop file below). For now it is the 'British shorthair' variant of Minecraft.
[SchrodingerChestPSD.zip](https://github.com/ScicraftLearn/Scicraft/files/7652429/SchrodingerChestPSD.zip)

I used the Minecraft default texture for the chest. However this is not exactly freely available... Can this pose an issue when we distribute the mod?

**Comment by IneMEGAmaxi** [comment]
.sjon file and updated .png:
[SchrodingerChest.zip](https://github.com/ScicraftLearn/Scicraft/files/7678235/SchrodingerChest.zip)
![SchrodingerChest](https://user-images.githubusercontent.com/29948516/145266829-1e3b0749-25bc-4969-953a-100b3f738105.png)

**Comment by IneMEGAmaxi** [comment]
updated files on drive (https://drive.google.com/drive/folders/1uwqHcqtD6bnJWiJuoSbflhcuYsGDsKAx)
