### ISSUE TITLE
Missing texture: Zombie scientific villager

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#288]
![afbeelding](https://user-images.githubusercontent.com/26555903/184363425-427c93df-95e5-4a37-b323-dbb2b8364cac.png)

**Comment by RandyParedis** [comment]
![villager](https://user-images.githubusercontent.com/25817922/187994503-88c0b91e-4d71-412f-966c-3d26c40b4cfc.png)

Try this perhaps?

**Comment by pixar02** [comment]
![2022-10-10_17 56 04](https://user-images.githubusercontent.com/7142721/194907407-4051fbca-b6b2-4100-8124-cc93ed5bde1d.png)

**Comment by pixar02** [comment]
White hands?? wrong/bad overlay for zombie
