### ISSUE TITLE
Schrödinger's Cat: Craftable

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#29]
Do we make the box of Schrödinger's Cat craftable. If so, what is a good recipe?

**Comment by RobbeNooyens** [comment]
Ideas for the recipe:
- a cat spawn egg surrounded by planks
- a square of black concrete (as a 'black box')
- a poisoned potato or something else inedible surrounded by planks

**Comment by JoeyDP** [comment]
The potato is also a good idea as alternative to the potion. Or rotten flesh but that's less obvious despite cats actually eating it.

And you wouldn't be able to leave the empty bottle behind..
