### ISSUE TITLE
Using the subatomic portal in the nether and end transports you to the same coordinates in the overworld when coming back

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#307]
Going to the nether (for example to x =50, z = 0) then using a subatomic portal to transport to the subatomic dimension, then using it again, teleports you to the overworld, at the coordinates x = 50, z = 0.

Going to the end, using an end gateway to get to x = 300, z = 1000, then going in the subatomic dimension and back out again teleports you to the overworld coordinates x = 300, z = 1000

**Comment by smtdm** [comment]
A possible solution is letting the portal block explode when it is used in the nether or end, like beds or respawn anchors.

**Comment by Sam-Roggeman** [comment]
portal exploding on use in other dimensions
