### ISSUE TITLE
Indicate how to get the next stable atom

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#311]
If an unstable atom is present in the Bohr Building plate, indicate if the closest stable atom is with more or less neutrons.

The amount of protons is always correct (it indicates the name of the atom). 

For example, when 6 protons and 4 neutrons are present (Carbon 10) the next stable is with 6 neutrons (Carbon 12)

**Comment by MaksimKarnaukh02** [comment]
Dit is geïmplementeerd, maar voor de één of andere reden zijn er een aantal atomen (ik heb enkel As en Tc gevonden tot nu toe), waarbij die een stabiel atoom wilt zoeken om te bepalen hoeveel neutronen moeten toegevoegd worden, maar hij neemt het foute, waardoor hij vraagt om 0 neutronen toe te voegen...

**Comment by MaksimKarnaukh02** [comment]
Het is nu opgelost. In de zelfgemaakte nuclide tabel kan een nucleus nu verschillende decaymodes bijhouden voor zich.
