### ISSUE TITLE
Define the look and feel for flying electrons

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/MineLabs#35]
For now flying electrons are rendered as the item itself, however this doesn't have to be the case. Some options for customization are:
- Custom sound when throwing electron (zap sound? Adaptation of lightning strike?)
- Custom particles when hitting a block (can be same as texture or completely different (sparks?)
- Custom texture of electron in air

See #17 also

**Comment by RandyParedis** [comment]
Is this issue still important/required?

**Comment by JoeyDP** [comment]
Nope
