### ISSUE TITLE
atom textures

### ISSUE THREAD

**Issue by IneMEGAmaxi** [ScicraftLearn/MineLabs#352]
make consistent/ text colors/ visualise electrons better ..?

**Comment by RandyParedis** [comment]
I am not sure I understand what you mean...

For consistency: The [CPK coloring table](https://en.wikipedia.org/wiki/CPK_coloring) has been used.
Text colors: Normally, White, Beige and Lime should have black letters; all others should have white letters. Maybe Yellow can change to black as well?
Electrons: Maybe they should be larger indeed. Low priority is adding an animation of actually rotating electrons, but that does not work with the current layered system.

**Comment by IneMEGAmaxi** [comment]
![image](https://user-images.githubusercontent.com/29948516/188963629-6e5209f9-d154-401f-bd8f-346f96ab98f4.png)
I actually would try to go for all white on the text if possible
also I wonder if the texture size could be smaller?
Maybe someone can try some variations

**Comment by smtdm** [comment]
Lead (Pb) and Tin (Sn) both may have 4 valence electrons on their texture.

**Comment by IneMEGAmaxi** [comment]
![image](https://user-images.githubusercontent.com/29948516/188989704-151840dc-4763-4735-9062-da03cb05299c.png)
this is a 32x32 example, using the minecraft font

**Comment by RandyParedis** [comment]
I had no idea I was working on a 38x38 texture; my bad!
All white sounds good; however, I am afraid that the white, yellow and lime backgrounds will make some of it unreadable. What do you think of a black border around the letters?

I like the 32x32 layout; it is slightly cleaner. Will change it all later today!
