### ISSUE TITLE
LCT/ICT and new atoms

### ISSUE THREAD

**Issue by IneMEGAmaxi** [ScicraftLearn/MineLabs#354]
check which of the newly added atoms should be allowed in the LCT/ICT

**Comment by smtdm** [comment]
For the LCT: only atomtypes     
POST_TRANSITION_METAL,
NON_METAL,
NOBLE_GAS
are allowed
 (see java/be/uantwerpen/minelabs/crafting/molecules/Atom.java for all the atom types)
