### ISSUE TITLE
refactor: put all atoms (item/ models/ textures) in subdirectories

### ISSUE THREAD

**Issue by IneMEGAmaxi** [ScicraftLearn/Minelabs#355]
I'm too lazy, thanks!

**Comment by MajaVerstraeten** [comment]
The folders "blockstates" "models" and "textures" inside "resources" are divided into subfolders. The paths in the code are updated.

To do: the pion texture is not working and the salt_wire

**Comment by IneMEGAmaxi** [comment]
thanks so much!
I fixed the salt_wire and the pions.

Now I just noticed that the lang files also use the identifiers, so they will need to be updated as well

**Comment by pixar02** [comment]
> thanks so much! I fixed the salt_wire and the pions.
> 
> Now I just noticed that the lang files also use the identifiers, so they will need to be updated as well

Lang files, recipes, loottables, tags. (propably everything in data needs some changes)
Currently breaks colored fire, because of lang and tags.
