### ISSUE TITLE
electron blockentities crash the client (Multiplayer)

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#372]
When placing several electrons in the world, the client crashes with the error:

`The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2350.method_10163()" because "blockEntity.movement_direction" is null`

**Comment by smtdm** [comment]
@ferriarnus ? Can you look at this?

**Comment by ferriarnus** [comment]
Vreemd. Ik weet niet of ik tijd heb om hier nu naar te zoeken. Een idee is oftewel een null check, een ander idee is movement_direction een default te geven. Direction.NONE bestaat denk ik?
