### ISSUE TITLE
something something shadow renders weird

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#405]
![afbeelding](https://user-images.githubusercontent.com/26555903/195447244-de868f13-4978-4456-9e80-98f344b591bd.png)

**Comment by RandyParedis** [comment]
Wontfix, as it is a bug in Minecraft itself.

![2022-10-13_23 45 29](https://user-images.githubusercontent.com/25817922/195727050-749276e0-3a49-4509-82df-48bf85485896.png)
