### ISSUE TITLE
Add lasertool to the MineLabs creative tab

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#424]
Currently the lasertools are located in the "tools" tab. It would make sense if the lasertools are also added to the "Minelabs" tab.

![afbeelding](https://user-images.githubusercontent.com/26555903/197782710-df024e79-7d12-414c-bcd7-d3a20f0650f8.png)

**Comment by vatsal2908** [comment]
Hey, can you assign this issue to me?

**Comment by vatsal2908** [comment]
Hey, can you please guide me a little because this is my first contribution .
