### ISSUE TITLE
Mologram does not update after hopper pulls out item

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#429]
![afbeelding](https://user-images.githubusercontent.com/26555903/200372509-f67ca09e-ff67-4687-afc2-7feb9301ffc9.png)
![afbeelding](https://user-images.githubusercontent.com/26555903/200372528-a495aba4-3a9d-4e95-8688-1b39e6a9adbe.png)

**Comment by pixar02** [comment]
It's a server/client desync.

**Comment by JoeyDP** [comment]
For more info on how to fix this, contact me.

**Comment by JoeyDP** [comment]
The fabric documentation about it is here: https://fabricmc.net/wiki/tutorial:blockentity#:~:text=not%20been%20done.-,Sync%20data%20from%20server%20to%20client,-The%20data%20is

Please also take a look at the documentation of these two functions when you use the named sources (genSources task and linking the sources in IDE).
