### ISSUE TITLE
Add atom coordinates for binary covalent molecules. (Part 5)

### ISSUE THREAD

**Issue by pixar02** [ScicraftLearn/MineLabs#433]
Look up databases of atom coordinates (in molfiles or POSCAR-files) and add these coordinates to the molecule JSON's. These coordinates wil later be used to render the molecules in the mologram.
See assets -> molecule -> ch4.json for an example.
AN example JSON can also be found in the drive
https://drive.google.com/drive/folders/1Ths7CnTrBBZrDF6zMR6VJyQovy-3b0fv

Fix issue #224 ,#241 , #242 , #243 and #421 first before this issue.

list of molecules:

- [x] LiCl
- [x] SrCl2
- [x] strontium nitrate **(also formula in a string format?)**
- [x] CaCl2
- [x] Na2CO3
- [ ] ~~borax **(also formula in a string format?)**~~
- [x] CuSO4
- [x] BH3O3
- [x] CuCl2
- [x] K2SO4
- [x] KNO3
- [x] KCl
- [x] MgSO4

**Comment by MajaVerstraeten** [comment]
LiCl is an ionic bond
In Na2CO3, CO3 is a covaent bond that has ionic bonds with the two Na.

Should a bond be drawn for ionic bonds?

**Comment by pixar02** [comment]
@smtdm

**Comment by smtdm** [comment]
Borax is to big to be useful.
skip it
