### ISSUE TITLE
[Bug] Entropy Creeper: Snowy grass does not update after entropy creeper explosion

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#448]
![afbeelding](https://user-images.githubusercontent.com/26555903/203651679-f59eaca6-cd87-44d0-af2b-ee39954107a2.png)

**Comment by smtdm** [comment]
Possible fix: neighbour updates when entropy creeper explodes

**Comment by JoeyDP** [comment]
See Fill command for how to perform mass block updates.
