### ISSUE TITLE
Bohr Plate incorrect hopper interaction

### ISSUE THREAD

**Issue by pixar02** [ScicraftLearn/Minelabs#449]
### **Inserting**:
Bohr plate allows hopper insertion into the wrong Slots.
Make sure that the slot it is inserting to is the correct one.
Slots 0,1 and 2 : Protons 
Slots 3, 4 and 5 : Neutrons
Slots 6, 7 and 8 : Electrons

Anti particles remove 1 AND consumes anti particle (AntiProton, AntiNeutron, Positron).

### **Extracting**:
Extracts from all slots...
Make it so it only extracts when the Atom is collectable (see method: `BohrBlockEntity.isCollectable()`)
Also clear the items required for making of the Atom.

### **Automation**:
When Atom is collectable allow for a Comparator output. That way Advanced blocks can extract a specific Atom.
_crafting system steps (example): insert all required Protons, insert all required neutrons, insert all required electrons_
See Extracting for info when this should be true.

### Side Effects:
- Server/Client desync

**Comment by JoeyDP** [comment]
Hopper interaction with BBP doesn't look useful at the moment to me. It would look weird with the current model, it wouldn't be practical to use and extraction is also not logical to the user.
