### ISSUE TITLE
Entropycreeper makes holes in the subatomic floor and destroys portal.

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/MineLabs#452]
The entropycreeper can be pushed into the subatomic portal, teleporting it to the subatomic dimension. If it explodes near the portal it can create holes in the subatomic floor, due to the potal generating in the subatomic floor, thus replacing it with salt blocks. These salt blocks can get moved, creating the holes. The player cannot get back to the overworld due to the portal being broken. 

Possible fixes:
- entropy creepers cannot go through subatomic portals
- make salt blocks unmovable by the entropycreeper

**Comment by JoeyDP** [comment]
Can't we also make the floor blocks unmovable and unable to be replaced, as was intended in the first place?
