### ISSUE TITLE
Testing Pokéball pointcharge - blockentity with a higher charge

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#465]
A point charge is a blockentity with an inventory with 1 (?) slot. In this inventory the player can put charged items (electrons, positrons,...). The blockentity then gets the charge of the amount of particles that are stored in the block. 

The point charge reacts to the surroundings as a charge would react (movement, electric field sensor, timefreeze block).

Further discussion needed ...

**Comment by JoeyDP** [comment]
Needs to be tested and new issues made.
