### ISSUE TITLE
Confusing description of the salt block

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#494]
Salt block has two separate recipes. This is confusing because the description notes 4x NaCl, but it can also be crafted with 9x salt dust
![afbeelding](https://user-images.githubusercontent.com/26555903/226108347-fbb77b84-67d3-4bf0-878a-99f5ff7ae95d.png)
![afbeelding](https://user-images.githubusercontent.com/26555903/226108362-d41c2a05-a1f5-4d77-964a-c5e72270c9c8.png)

**Comment by JoeyDP** [comment]
The easiest solution seems to be removing one of the two recipes, as they seem mutually exclusive. Is salt dust craftable from NaCl? Then the recipe with 9 dust seems best to keep. What do you think @pixar02 and @smtdm ?
