### ISSUE TITLE
Mologram: atom sizes

### ISSUE THREAD

**Issue by IneMEGAmaxi** [ScicraftLearn/Minelabs#504]
The atom size can be one of 3 different values: S, M, L
(check with the chemist which atom should be which)

**Comment by JoeyDP** [comment]
> the chemist

**Comment by JorenFa** [comment]
Placeholder code is done, all I need now is to know what size 'S', 'M' and 'L' are, and which atoms should be specified as L.

**Comment by JoeyDP** [comment]
Could you try having the current radius be M and choose something smaller and larger for S and L?

There's no scientific background to base this on so I think it's best if you just look that there remains enough distance betweeen atoms for the L atoms and that the (triple) bonds remain connected and pretty with the S atoms. Comment some screenshots here for feedback of [The Chemist]((@smtdm)).
