### ISSUE TITLE
Networking code rewrite crashes datagen

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#518]
In the bohr_plate branch: usage of client only code in the server makes the runDatagen crash. This is caused by moving networking code.

**Comment by pixar02** [comment]
> In the bohr_plate branch: usage of client only code in the server makes the runDatagen crash. This is caused by moving networking code.

Look at the DataPackets.
Either don't put them in Networkconstants. (keeping the Packets in Client)
Or Split the Packet into a S2C and a C2S. (and figure out how to use it then)
