### ISSUE TITLE
Bohr plate entity: test for undesired effects

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#521]
Check whether none of the default entity code is active for this 'fake' entity. Examples:

- name tags
- damaging
- picking up items
- moving the entity
- destroying the entity somehow
- ...

Using F3 + B can help show the bounds of the entity.

**Comment by smtdm** [comment]
Name tags - no effect
Damaging - only player induced damage (melee, bow and arrow, trident)
!crosbow with firework DOES NOT WORK
picking up items - 
moving the entity - entity breaks and does not come back
