### ISSUE TITLE
Advancement: Bohr-ing

### ISSUE THREAD

**Issue by IneMEGAmaxi** [ScicraftLearn/Minelabs#530]
still triggers when you right-click the Bohr blueprint.
It should now trigger when the Bohr entity catches a particle you throw at it

**Comment by JoeyDP** [comment]
You still right click at the bohr plate to craft an atom, so that would be fine, but it probably also triggers when you right click and it doesn't work. Will probably need a custom criterion again.

**Comment by JorenFa** [comment]
So what is the idea of this advancement? Is it when you add a particle, or when you take out your first new atom?
The initial issue sais when you throw a particle at it, but then the more recent comment talks about taking the atom out..
So which one is it? I'll start working on this tomorrow.

**Comment by JoeyDP** [comment]
When adding something to the inventory seems like a better idea. There are already a bunch of achievements for obtaining atoms which would fire at the same time otherwise.
