### ISSUE TITLE
Set limit to capacity in bohr blueprint

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#546]
What should the limit be @IneMEGAmaxi ?

**Comment by IneMEGAmaxi** [comment]
https://en.wikipedia.org/wiki/Oganesson
176 neutrons is max

however, we will probably not implement this element...

**Comment by JoeyDP** [comment]
Perhaps we can also look at a maximum number of protons/neutrons and electrons we will render. If we continue with the orbits, what would a logical cutoff point be then?

**Comment by IneMEGAmaxi** [comment]
looking at the largest non-synthetic element (Pu) we get: 94 protons, 150 neutrons
however from the rendering point of view, closed shells are more interesting, this would be the largest noble gas: Og (118 protons 176 neutrons)

**Comment by JoeyDP** [comment]
The respective max values per shell would be as follows then right?
2, 8, 18, 32, 32, 18, 8

**Comment by IneMEGAmaxi** [comment]
Im honestly not that familiar with the shell model anymore..
the rows in the periodic table indicate:
2, 8, 8, 18, 18, 32, 32

**Comment by JoeyDP** [comment]
I just copied this: https://en.wikipedia.org/wiki/Electron_shell#List_of_elements_with_electrons_per_shell

Seems good to limit it to 7 shells and filling them according to this table (no idea if this is already the case) and setting the limit to 118 like you propose.

**Comment by JoeyDP** [comment]
Setting limit of neutrons to 176 based on the `Og` element.
