### ISSUE TITLE
Remove uantwerpen from package structure: should be be.minelabs

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#567]
Use IDE to refactor.

**Comment by pixar02** [comment]
would it become:
`be.minelabs.minelabs` ?
making it: 
`be.minelabs.minelabs.Minelabs`
`be.minelabs.minelabs.MinelabsClient`
`be.minelabs.minelabs.MinelabsDatagen`

**Comment by JoeyDP** [comment]
One minelabs is enough for me :p

In java the convention is to use your website in reverse, so: be.minelabs.

That's also why the Minecraft source code is in net.minecraft.
