### ISSUE TITLE
Take inventory of all warnings and errors during startup

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#568]
Minecraft logs a lot of warning and even minor errors when starting up. Things like missing textures, models, sounds and other resources as well as errors in the existing ones.

Group these problems into issues (not one issue per error please) so they can be resolved structurally.

**Comment by BertJorissen** [comment]
Made issues #571 #572 #573 #574 #575 #576 #577 #578 #579 #580 and #581 . Some issue are related, but I think most of the errors are independent of each other.

**Comment by JoeyDP** [comment]
Perfect, thanks! Most issues are included in this sprint for now, but it's okay if we need to push some of them back to next sprint. Closing this issue.
