### ISSUE TITLE
Run: Bohr model

### ISSUE THREAD

**Issue by BertJorissen** [ScicraftLearn/Minelabs#577]
During the run of the client, the following warning appears:
_[XX:XX:XX] [Worker-Main-24/WARN] (Minecraft) Unable to resolve texture reference: #missing in minelabs:block/bohr_block
[XX:XX:XX] [Worker-Main-24/WARN] (Minecraft) Unable to resolve texture reference: #missing in minelabs:block/bohr_block_unstable
[XX:XX:XX] [Worker-Main-24/WARN] (Minecraft) Unable to resolve texture reference: #missing in minelabs:block/bohr_block_ready_

Related to https://github.com/ScicraftLearn/Minelabs/blob/6a2ef364c216b07c2c6e571277a2a65bb1125992/src/main/resources/assets/minelabs/models/block/bohr_template.json#L27

**Comment by IneMEGAmaxi** [comment]
Those lines can be safely removed
