### ISSUE TITLE
Run: texture mologram sphere

### ISSUE THREAD

**Issue by BertJorissen** [ScicraftLearn/Minelabs#578]
During the run of the client, the following warning appears:
_[XX:XX:XX] [Worker-Main-24/WARN] (Minecraft) Texture minelabs:block/mologram/sphere with size 2x2 limits mip level from 4 to 1
[XX:XX:XX] [Worker-Main-24/WARN] (Minecraft) minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 1, because of minimum power of two: 2_

Related to the file at https://github.com/ScicraftLearn/Minelabs/blob/6a2ef364c216b07c2c6e571277a2a65bb1125992/src/main/resources/assets/minelabs/textures/block/mologram/sphere.png , possible solution: make png 8x8 pixels.

**Comment by JoeyDP** [comment]
Seems rather important if this prevents mipmapping of other textures. Can you take a look at this @IneMEGAmaxi ?

**Comment by IneMEGAmaxi** [comment]
making the texture 8x8 will indeed fix this.
this can be done in ms paint, no need for team art :)
