### ISSUE TITLE
Run: shader entity translucent

### ISSUE THREAD

**Issue by BertJorissen** [ScicraftLearn/Minelabs#579]
During the run of the client, the following warning appears:
_[XX:XX:XX] [Render thread/WARN] (Minecraft) Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program._

No idea what to do with this.

**Comment by JoeyDP** [comment]
Is this even an issue we caused? I'd be okay with dropping this and seeing if it persists after the next MC version update. Feel free to close.
