### ISSUE TITLE
Run: flowing acids

### ISSUE THREAD

**Issue by BertJorissen** [ScicraftLearn/Minelabs#580]
During the run of the client, the following error appears:
_[XX:XX:XX] [Worker-Main-57/ERROR] (Minecraft) Couldn't load tag minelabs:acid as it is missing following references: minelabs:acid (from Minelabs), minelabs:flowing_acid (from Minelabs)_

Possibly related to https://github.com/ScicraftLearn/Minelabs/blob/6a2ef364c216b07c2c6e571277a2a65bb1125992/src/main/resources/data/minelabs/tags/fluids/acid.json#L5

**Comment by JoeyDP** [comment]
Could you check this out @RobbeNooyens ?
