### ISSUE TITLE
Blocks can be placed in the BBP entity

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#590]
Some blocks can be placed on the BBP. They are placed inside the entity, meaning they can only be broken from below, when the BBP is removed, or when they are pushed out by a piston.

Figure 1
![afbeelding](https://user-images.githubusercontent.com/26555903/230388324-9cb2dd7b-e245-477a-90b9-fbb02b30a8b1.png)

Figure 2
![afbeelding](https://user-images.githubusercontent.com/26555903/230388391-db15c9ea-31d4-4239-8568-bc4847684f99.png)

Figure 3
![afbeelding](https://user-images.githubusercontent.com/26555903/230388461-8259cb71-7b75-4ab1-84d6-320c3eb48f01.png)

**Comment by JoeyDP** [comment]
Perhaps we can make the entity only interactable when it is not empty. This way the blocks would be accessible when the bohr blueprint is empty. Would this be a fitting solution?
