### ISSUE TITLE
Bohrplate implement stability and integrity

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#591]
Bohrplate instability keeps counting down without ever breaking.
When removing the atom and replacing it, the progress does **not** reset.

![afbeelding](https://user-images.githubusercontent.com/26555903/230391516-1189b3d6-d906-4cd8-984f-651b1f6a4284.png)

**Comment by JoeyDP** [comment]
Sorry I am hijacking this issue.

Implement stability and integrity mechanics in entity. Idea: Degree of instability determines how heavy the rendering should display shaking or other instability effects. Once instability hits a threshold, integrity starts counting down at a fixed rate independent of stability (for example 10 seconds). After this all contents are dropped. Getting stability back under control resets the timer.

**Comment by JoeyDP** [comment]
For protons and neutrons: use the existing nucleus stability code.
For electrons:
 - [0-p] = stable
 - [p+1 - p+8] = degree of instability shown, bar red
 - more: don't accept electrons or anti-protons so cannot exceed -8 charge.
 - from p+6 start the integrity timer

**Comment by JoeyDP** [comment]
Implement new class `AtomConfiguration` (name pending) to put this logic in. Also add caching to this object. Move some of the code from `BohrBlueprintEntity` and have it return this instance.
