### ISSUE TITLE
Bohr Blueprint: cannot remove protons, neutrons and electrons when the starting point was an atom

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#592]
When starting from an atom, no protons, neutrons and electrons can be removed with their respective anti-particles.

**Comment by JoeyDP** [comment]
This is intentional to prevent unexpected behaviour of the 'undo' feature. Atoms are for example also only insertable as the first item.  Need to discuss what we want to happen f you do allow anti particles to affect atoms before we can implement something. This is not a bug.
