### ISSUE TITLE
balloon: lead on a fence 

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#595]
Attaching an animal to a fence with a lead, and then attaching attaching a balloon to th animal results in a lead on a fence, without an animal attached.

![afbeelding](https://user-images.githubusercontent.com/26555903/230402480-00aefdcb-141c-4b46-b16f-2e25bedcc8c5.png)

**Comment by RandyParedis** [comment]
Likely the same bug as connecting multiple balloons to a single animal and having not all leads rendered...

![2023-11-08_20 11 31](https://github.com/ScicraftLearn/Minelabs/assets/25817922/e4f46db3-30e3-4c37-b8b9-c0f66242a322)
