### ISSUE TITLE
Merge relevant branches. Delete others.

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#597]
By the end of alpha all branches need to be up to date with main and cannot be ahead. All WIP branches need to be merged or removed from remote. Decide which branches are still needed and finish + merge them. Other branches can be cached locally for reference but will be removed from the repository.

Doing this will allow us to more easily update to the latest Minecraft version and perform structural changes that would make merging those branches afterwards very impractical.

**Comment by JoeyDP** [comment]
@pixar02 can I assign you to this? The majority of branches are yours I believe and you can ping on Discord for the other ones.

**Comment by pixar02** [comment]
deleting some...
Just to make new ones XD
