### ISSUE TITLE
Lighter color items on first frame after opening lab drawer or cabin

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#612]
In the first frame after opening a lab cabin or drawer, some items in the inventory have a lighter color.
Affected items are:

- all the lab blocks
- microscope
- tube rack
- bunsen burner
- chests
- (probably more)

![afbeelding](https://user-images.githubusercontent.com/26555903/230723209-2abb7085-b685-4882-b8d2-6c605ff948d7.png)
![afbeelding](https://user-images.githubusercontent.com/26555903/230723215-6b960b6a-8945-451e-89cc-ec39b5814819.png)

https://user-images.githubusercontent.com/26555903/230723225-31546fd7-3e29-45cb-bc89-efff5fb7b12e.mp4

**Comment by smtdm** [comment]
This also happens when opening a chest and dispenser.

**Comment by pixar02** [comment]
Also happens on minecraft items.
This might be an issue we cannot fix.

**Comment by JoeyDP** [comment]
Ine says: ":("
