### ISSUE TITLE
Cosmetics: breaking particles of bunsenburner contain purple

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#633]
Breaking particles of bunsenburner contain purple. The block itself does not.
![afbeelding](https://user-images.githubusercontent.com/26555903/231173152-b3932442-97b1-44d7-84a3-87b8613fcaec.png)

**Comment by JoeyDP** [comment]
Those are probably the parts of the texture that contain the old flame that is no longer used. @RandyParedis can you update the texture?

**Comment by RandyParedis** [comment]
![bunsen_torch](https://user-images.githubusercontent.com/25817922/233840728-89ec119d-12f1-4c0a-9cdd-a36664a811d8.png)

Purple-free texture :)
