### ISSUE TITLE
Bohr plate: Funky Transparency rendering

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#641]
Transparency of the lines causes the protons, neutrons and electrons to be partly transparent.

![afbeelding](https://user-images.githubusercontent.com/26555903/231874804-c67ea601-31df-4434-abb2-3ee375052688.png)

**Comment by JoeyDP** [comment]
Look into whether this can easily be solved. Don't spend more than two bananas on this if it gets too complex.

**Comment by JoeyDP** [comment]
Can't reproduce anymore so I think it got fixed when I updated the normals and switched to the LINE renderer iso LINE_STRIP.

**Comment by JoeyDP** [comment]
Caused by Minecraft renderer internals. With fabulous rendering it does work. Can't fix.
