### ISSUE TITLE
bohr plate: increase max capacity

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#645]
Current max protons, neutrons and electrons is set to that of Oganesson (p:118 n: 176). To allow the player to experiment with configurations around this atom I suggest the following capacities:

- protons: 118
- neutrons: 180
- electrons: 118 + 8

We still limit the protons which allows us to render the atom symbol at all times. Otherwise we need to make edge cases for elements > 118. The neutron count is rounded to 180 and we have stability info from the stable diagonal chart. Electrons are capped at their max divergence from protons which will be implemented this sprint.

**Comment by JoeyDP** [comment]
@smtdm and @IneMEGAmaxi opinions? I based these numbers more from a practical point of view than a scientific one. Is this ok?

**Comment by JoeyDP** [comment]
On second thought, I think we can just set everything to 200 and have the instability mechanic handle it.

**Comment by IneMEGAmaxi** [comment]
You know @smtdm is gonna break that, right?

**Comment by JoeyDP** [comment]
I'm counting on it
