### ISSUE TITLE
Magnet: Texture with animation

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#660]

**Comment by RandyParedis** [comment]
[star.zip](https://github.com/ScicraftLearn/Minelabs/files/11303765/star.zip)

Here are the MC files. Not sure which branch and/or item to add them to.
Blame @IneMEGAmaxi for calling it "star" ;)

**Comment by IneMEGAmaxi** [comment]
> [star.zip](https://github.com/ScicraftLearn/Minelabs/files/11303765/star.zip)
> 
> Here are the MC files. Not sure which branch and/or item to add them to. Blame @IneMEGAmaxi for calling it "star" ;)

Not my fault that calling it 'black hole' makes you guys giggle that much...

**Comment by JoeyDP** [comment]
> Not my fault that calling it 'black hole' makes you guys giggle that much...

Oh but star can mean all sorts of things too you know ;)

**Comment by IneMEGAmaxi** [comment]
Where can I contact HR?
