### ISSUE TITLE
Bohr plate: Improve coordinates of Nucleus with Fibonacci Grid Sphere

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#673]
**Is your feature request related to a problem? Please describe.**
Current sphere points are not uniform

**Describe the solution you'd like**

- https://www.reddit.com/r/math/comments/94se5s/comment/e3ngdpe/?utm_source=share&utm_medium=web3x
- http://extremelearning.com.au/how-to-evenly-distribute-points-on-a-sphere-more-effectively-than-the-canonical-fibonacci-lattice/#:~:text=Mapping%20the%20Fibonacci%20lattice%20(aka,distribute%20points%20on%20a%20sphere.

**Comment by JoeyDP** [comment]
Can make the radius very large to see difference

**Comment by JoeyDP** [comment]
https://stackoverflow.com/questions/9600801/evenly-distributing-n-points-on-a-sphere

**Comment by IneMEGAmaxi** [comment]
![Image](https://github.com/ScicraftLearn/Minelabs/assets/29948516/d4702dcd-0768-4acc-8003-3c5d8634cf73)

quite pretty

**Comment by JoeyDP** [comment]
See comments on: https://github.com/ScicraftLearn/Minelabs/commit/843df8d4c84a2229d10cdbc7eb02c3abe2f7ba17 for further improvements :D
