### ISSUE TITLE
Create textures for all atoms

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#690]
Is this manual work or do you use a datagen? Could easily be done since all info is available: symbol, color, number of valence electrons.

**Comment by RandyParedis** [comment]
The textures themselves must happen semi-manually to allow for font scaling, font colors and centering and such...

The layer files to link the valence electrons and such can be done using a datagen, given a table of atom, color, number of valence electrons.

**Comment by IneMEGAmaxi** [comment]
temporary stuff has been merged into main
Pierre generated the jsons
I made a single png texture "_" so that it would not display the missing texture.

Maybe we can divide the manual work for a later release?
