### ISSUE TITLE
[Bug] Mologram: molecules don't render

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#712]

**Comment by JoeyDP** [comment]
Seems to be caused by `sodium` being added. Custom portals API has included this in their latest version (https://github.com/kyrptonaught/customportalapi/blob/1.19.4/build.gradle).

Without sodium installed, the rendering works fine.

**Comment by pixar02** [comment]
Sodium has always been added by Custom Portals API. For some reason is has never actually been added to our project. Until now.

**Comment by JoeyDP** [comment]
Are you sure? I found this in their version history, which would explain the sudden issues: https://github.com/kyrptonaught/customportalapi/commit/78bd483efbf44e36a74af6c199bd424117883489

**Comment by pixar02** [comment]
https://github.com/kyrptonaught/customportalapi/blob/Legacy-1.19.X/build.gradle

API for 1.19 to 1.19.2
Also has `sodium` as dependency.
