### ISSUE TITLE
Translations: Use datagen to generate all missing translations

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Minelabs#722]
## For en_us and nl_be
1. Generate blanks for all items/blocks/... in the code.
2. Fill in existing values based on previous version of translation file.
3. Write back.

## For nl_nl
Just generate a copy of nl_be.
If possible: also add as first line a value that mentions this file is generated and will be overwritten with values of nl_be.

**Comment by pixar02** [comment]
Since we moved some items/blocks/... into subfolders the old translations are broken. 
We need to either remove them from the file and add them in the generator. 
OR
Update the "static" (old) file the use the new subfolders.

**Comment by JoeyDP** [comment]
It seems you manually put all items, blocks, groups etc. in the provider. Doesn't that defeat the purpose a bit? The idea was to automatically add entries based on the registered entities, i.e. fetch everything from the registry that is in the Minelabs namespace.

**Comment by pixar02** [comment]
Was just a way to get my head arround it. (needed to override the run() for the key gen)
Haven't done all the entries yet (only the blocks)

**Comment by pixar02** [comment]
see `lang/provider`

**Comment by JoeyDP** [comment]
Looks good! Could even not have empty strings as placeholder but the last part of the name instead.

Ps: in the function you made, don't cast to Identifier, as it needs to know what type the thing is.

**Comment by pixar02** [comment]
It's still a wip.
I know it needs the type, but the type `?` won't be seen as a type. It transforms it into a string which loses the namespace and type.
