### ISSUE TITLE
Update Q-field textures

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#727]
Something with UV-mapping and seeds and stuff

**Comment by IneMEGAmaxi** [comment]
UV mapping: not urgent
seeds: choose blockstate based on coordinates: is this possible?

**Comment by JoeyDP** [comment]
You can have rendering be based on the position, even with the same blockstate I believe. Mirrored textures need to be provided though. UV mapping might even make it harder because now we can pick and match different faces from the pool of standard and mirrored textures.

**Comment by JoeyDP** [comment]
It seems the rendering seed is only used for random selection of a weighted pool of variants in the vanilla renderer.

Will need to update blockstate and select corresponding mirrored/rotated model.
