### ISSUE TITLE
Refactor OrderedInventory

### ISSUE THREAD

**Issue by pixar02** [ScicraftLearn/Minelabs#757]
use `Inventories.readNbt()` and `Inventories.writeNbt()` Instead of making another class that does the same thing.

**Comment by JoeyDP** [comment]
We do still need it because it offers functionality such as listeners and the Inventory interface.

**Comment by pixar02** [comment]
If you want the `Listeners` use `SimpleInventory`.
There is no reason for `OrderedInventory`
`OrderedInventory` is already extended from `SimpleInventory`


`OrderedInventory` can just be replaced with `SimpleInventory`
And everywhere you are saying write/read nbt replace that with `Inventories.readNbt()` and `Inventories.writeNbt()`

**Comment by JoeyDP** [comment]
This seems like a pointless discussion to me. Do you have an explicit reason why we should not use this abstraction?

I like to have a class that has the same interface as SimpleInventory so I don't need to bother remembering to use the Inventories.readNbt function and also for other devs that might not know about this way of storing inventory NBT it is more clear.  The naming also makes explicit how the inventory will be stored, so you don't even have to look at the code to figure it out.
