### ISSUE TITLE
[Bug] Mologram: no 3d model

### ISSUE THREAD

**Issue by IneMEGAmaxi** [ScicraftLearn/Minelabs#801]
**Describe the bug**
Mologram does not show 3d model

**To Reproduce**
Compiled jar from git actions was used
Seems to work fine in dev environment

**Comment by pixar02** [comment]
The culprit lies here:
```java
BakedModel model = MinecraftClient.getInstance().getBakedModelManager().models.get(new Identifier(Minelabs.MOD_ID, "molecules/" + molecule.getMolecule().toLowerCase()));
```

**Comment by pixar02** [comment]
@JoeyDP 

``Map<Identifier, Resource> molecules = manager.findResources("models/molecules", (i) -> true);``
This map is empty when running outside of the dev environment.

Could you look into it ? I have no idea what needs to happen to fix it.
I tried: 
```java
Map<Identifier, Resource> molecules = manager.findResources("", (i) -> {
                    if (i.getNamespace().equals(Minelabs.MOD_ID) && i.getPath().contains("models/molecules")) {
                        Minelabs.LOGGER.info(i);
                        return true;
                    }

                    return false;
                }
        );
```
But this also doesn't fix the problem.
