### ISSUE TITLE
[Bug] Balloon: Balloon and dispensers

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#817]
**Describe the bug**
Using a dispenser to deploy a balloon crashes the game.

**Additional context**

[crash-2023-11-11_13.24.19-server.txt](https://github.com/ScicraftLearn/Minelabs/files/13325445/crash-2023-11-11_13.24.19-server.txt)

**Comment by pixar02** [comment]
@RandyParedis Was this fixed  ?

**Comment by RandyParedis** [comment]
Yes. Is fixed in latest PR.
