### ISSUE TITLE
[Bug] Quantum fields: inconsistent durability usage when breakign QF

### ISSUE THREAD

**Issue by smtdm** [ScicraftLearn/Minelabs#842]
**Describe the bug**
Breaking of QF sometimes consumes durability and somtimes does not.

consume durability:
- shears

dont consume durability
- regular tools (axe, pick, shovel, hoe, sword)

**Expected behavior**
pick a side, it is one or the other

**Comment by JoeyDP** [comment]
It's  a MC thing
