### ISSUE TITLE
Item: Erlenmeyer

### ISSUE THREAD

**Issue by RobbeNooyens** [ScicraftLearn/MineLabs#85]
In order to easily add gasses, it's useful to create a general erlenmeyer. The erlenmeyer is an item (a bottle can be used as a placeholder) that can both poor liquids on the ground and create gas particles. It's essentially a combination of a bucket and a lingering potion that can hold liquids and gasses.
Some information you should get from the abstract erlenmeyer:
- get the liquid or gas that's stored in the erlenmeyer
- whether it stores a liquid or a gas (or none)
- 'pour' behaviour for a liquid
- throw behaviour for a gas

Once the general erlenmeyer is done, you can create an empty erlenmeyer item.

It'd be useful to be able to create multiple erlenmeyers by stacking textures on top of eachother (like beds).

**Comment by JoeyDP** [comment]
See #87 for status on art.
