### ISSUE TITLE
Textures for Erlenmeyer

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/MineLabs#88]
See #85 for interactions and use cases.

**Comment by JoshuaMoelans** [comment]
First mockup texture [can be found here!](https://imgur.com/a/uT45awU)
Need to check with the Erlenmeyer development team, how they implemented their initial version (with fillings like potions → is it hard-coded texturing or some other approach?)

**Comment by pabloDeputter** [comment]
That looks good :)) Is it possible to make the bottle, cork and content 3 seperate png files?

**Comment by JoshuaMoelans** [comment]
> That looks good :)) Is it possible to make the bottle, cork and content 3 seperate png files?

Definitely! [Here you go](https://imgur.com/a/K9e89Ct)

**Comment by IneMEGAmaxi** [comment]
You can upload all assets to the art folder on the scicraft drive:
https://drive.google.com/drive/folders/1Du39gBYgN7K54aCWVz97C2Jo-UMqBt8U?usp=sharing
