### ISSUE TITLE
Salt dust

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/MineLabs#91]
- Create item: salt dust
   - add tooltip: NaCl
- Create block: salt dust
   - Placeable in world and connects like redstone dust, but without signal etc., purely esthetic.

**Comment by pixar02** [comment]
WIP

- [x] item and block exist
- [ ] add Tooltip
- [ ] redstone like texture
- [x] textures exist (Thanks @IneMEGAmaxi )
